---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: capi-pack-builder

inputs:
  - name: capi-ci
  - name: source-repository

outputs:
  - name: image

params:
  CONTEXT_PATH: null
  ADDITIONAL_ARGS: null

run:
  path: capi-ci/ci/oci/build-with-pack.sh
