---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: cf-for-k8s

inputs:
  - name: cf-for-k8s-ci
  - name: env-metadata
  - name: private-env-repo

params:
  REPO_SUBDIRECTORY:
  GIT_COMMIT_EMAIL: capi-bot@pivotal.io
  GIT_COMMIT_USERNAME: "CAPI CI Bot"

outputs:
  - name: updated-private-env-repo

run:
  path: cf-for-k8s-ci/ci/tasks/cake/commit-env-metadata.sh
