---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: cf-for-k8s

inputs:
  - name: capi-ci
  - name: capi-k8s-release

params:
  GKE_SERVICE_ACCOUNT_KEY:
  CLUSTER_NAME:
  GCP_ZONE:

run:
  path: capi-ci/ci/backup-metadata-generator/e2e-test.sh
