---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: cf-for-k8s

inputs:
- name: capi-ci

params:
  GKE_SERVICE_ACCOUNT_KEY:
  VELERO_SERVICE_ACCOUNT_KEY:
  VELERO_TEST_BUCKET:
  CLUSTER_NAME:
  GCP_ZONE:

run:
  path: capi-ci/ci/backup-metadata-generator/install-velero.sh
