
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: cf-for-k8s

inputs:
  - name: backup-metadata-generator
  - name: capi-ci

run:
  path: capi-ci/ci/backup-metadata-generator/run-backup-metadata-generator-unit-tests.sh
